// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApi.Data;

namespace ProductApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210531112423_int4")]
    partial class int4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductApi.Areas.Context.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Instock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Ham is traditionally pork cut from a hog’s hind leg that has been preserved through salting, smoking or curing. However, it’s also possible to get chicken ham, preserved in the same manner. Ham is available in a variety of flavours; some of my favourites are honey-glazed ham, Serrano ham, which is a Spanish variety, Prosciutto, an Italian dry-cured ham and Black Forest ham, a German variety. Ham can be served as is, or baked, boiled or fried. It works well with sweet potatoes, tomatoes and white wine.",
                            Enabled = true,
                            Image = "https://www.hungryforever.com/wp-content/uploads/2015/04/ham_compressed-293x300.jpg",
                            Instock = true,
                            Name = "Ham",
                            Price = "90"
                        },
                        new
                        {
                            Id = 2,
                            Details = "Salami is also traditionally pork, or beef, which is seasoned with garlic, minced fat, salt, spices, wines and a range of herbs. Popular salami varieties are chorizo, pepperoni (bet you’ve heard of that one) and Saucisson sec. Salami tastes good on pizzas, in pastas, or simply in sandwiches.",
                            Enabled = true,
                            Image = "https://www.hungryforever.com/wp-content/uploads/2015/04/sliced-salami_compressed-300x214.jpg",
                            Instock = true,
                            Name = "Salami",
                            Price = "150"
                        },
                        new
                        {
                            Id = 3,
                            Details = "Either beef or pork is slow roasted, and served as a whole meal. Leftovers are then used in sandwiches and other recipes. Roast beef is the signature national dish of England, so if you’re hosting a British themed party, be sure to serve some up.",
                            Enabled = true,
                            Image = "https://www.hungryforever.com/wp-content/uploads/2015/04/beef_compressed-300x208.jpg",
                            Instock = true,
                            Name = "Roast Meat",
                            Price = "120"
                        },
                        new
                        {
                            Id = 4,
                            Details = "To prepare traditional meatloaf, beef is ground, mixed with spices and herbs, formed into a loaf shape and then baked or smoked. Meatloaf can also be made from lamb, pork, seafood, veal, venison and poultry. It can be served with rice or potatoes with a side of veggies, or spread on a sandwich.",
                            Enabled = true,
                            Image = "https://www.hungryforever.com/wp-content/uploads/2015/04/meatloaf_compressed-300x201.jpg",
                            Instock = true,
                            Name = "Meatloaf",
                            Price = "70"
                        },
                        new
                        {
                            Id = 5,
                            Details = "Bierwurst is a German sausage seasoned with pepper, mustard seeds and paprika. It is often eaten as a snack with beer.",
                            Enabled = true,
                            Image = "https://www.hungryforever.com/wp-content/uploads/2015/04/bierwurst_compressed-300x225.jpg",
                            Instock = true,
                            Name = "Bierwurst",
                            Price = "50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
